name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem

    - name: Connect to EC2 and run commands
      run: |
        ssh -t -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@ec2-54-238-41-185.ap-northeast-1.compute.amazonaws.com << 'EOF'
        # Gitディレクトリを安全なディレクトリとして設定
        git config --global --add safe.directory /home/ec2-user/ForGithubAction
        # リポジトリを更新
        cd /home/ec2-user/ForGithubAction
        git pull origin main
        EOF
