name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem

    - name: Connect to EC2 and run commands
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@your-ec2-public-ip << 'EOF'
        cd /home/ec2-user/ForGithubAction
        git pull origin main
        # 必要なコマンドをここに追加(EOFの手前まで)
        EOF

