name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # PEMファイルを作成
      - name: Create PEM file
        run: echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem

      # ファイルに適切な権限を設定
      - name: Set permissions for PEM file
        run: chmod 600 ec2-key.pem

      # EC2にSSH接続してコマンドを実行
      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@ec2-54-238-41-185.ap-northeast-1.compute.amazonaws.com 'your-commands-here'
